### ISSUE TITLE
[range] query does not support [execution]

### ISSUE THREAD

**Issue by andrewthad** [bitemyapp/bloodhound#122]
This might be an issue only with elasticsearch 2.0+, but when I do a query that involves a range filter, I get this error:

```
[range] query does not support [execution]
```

I have a branch that provides a fix for this that I'm working on.

**Comment by bitemyapp** [comment]
We don't yet officially support Elasticsearch 2.X, partly because AWS is still on 1.X. This'll be something to track for a move to 2.0 I think.

**Comment by WraithM** [comment]
What's the status of ES 2.x? I'm trying to use `bloodhound` with ES 2.4. Mostly everything works except this issue.

**Comment by MichaelXavier** [comment]
The plan is we have a person ( @bermanjosh ) who is working towards getting our first secondary version support for ES5. When that gets released, if there is additional work to get it to work on 2.0, it will be accepted as a PR. Depending on how it turns out and my available time, I may be one of those people contributing to 2.0 development. You should keep an eye on the #158 ticket.

**Comment by andrewthad** [comment]
By the way, here's my commit that adds this in case it's helpful: https://github.com/andrewthad/bloodhound/commit/604392f6aff240b0a9587fa529257c5e6125d170

**Comment by MichaelXavier** [comment]
Curious if version 0.13.0.0 solves your problem if you use the V5 module.

**Comment by WraithM** [comment]
At least for me on `0.13.0.0` with the V5 module on Elasticsearch 2.4, I no longer have this problem.

**Comment by bitemyapp** [comment]
Labeled as 2.x, closing as resolved. We'll need a contributor and a handful of problems to solve to justify the V2 module but it's on our radar.
