### ISSUE TITLE
Why is `m Reply` the return type of most functions ?

### ISSUE THREAD

**Issue by bartavelle** [bitemyapp/bloodhound#144]
I would guess that the answer is that ES responses are not properly documented, so it is really annoying to write code that will break between versions (this happened to me a few years ago, when I wrote `hslogstash`).

If that is the main problem, I would like to propose one of the following solutions (for which I would submit a PR):

 * Replace `Reply` with a type that is a little easier to process
 * Add functions that convert to that type

Given that I also have limited time, I would suggest PR'ing something like :

    bulk :: MonadBH m => Vector BulkOperation -> m Vector (DocId, BulkOperationResult)

    data BulkOperationResult = Success ShardInfo
                             | Failure1 FailureDetails1
                             | Failure2 FailureDetails2
                             | UnknownFailure Value
                             | UnreadableReply Reply

    data ShardInfo = ShardInfo { shardSuccessful :: Int, shardFailed :: Int, shardTotal :: Int }

Where `Failure1`, `Failure2`, etc. would be failures that are known and properly decoded, `UnknownFailure` would return the json-decoded response for other failures. `UnreadableReply` would be used when a reply can't be decoded.

**Comment by bitemyapp** [comment]
@MichaelXavier and I have talked about making the return types more precise/informative, so I'm pinging him.

**Comment by MichaelXavier** [comment]
The utilities are there to do this its just that the API of this library is sot of evaluated as needed. Take a look at `parseEsResponse :: (MonadThrow m, FromJSON a) => Reply -> m (Either EsError a)`. Usually in my PRs when I add a new API I'll have it return `Either EsError SpecificTypeForThisAPI`. Older functions in the library still return a Reply but could be upgraded to returning a richer type just as soon as you define a richer type and a `FromJSON` instance for it. We have a fairly wide range of ES versions in our travis build matrix so usually I'll define the types for my version (since the docs will never say), let travis build it and then go back and make fields that are optional for older (or newer) versions optional in the types and voila!

So if that sounds good, I would move that we could close this ticket and you open tickets for the APIs that you specifically need replies for. You could add them yourself or if I've got some spare time I may implement them for you (as long as they're not as massive as the stats API!)

**Comment by bartavelle** [comment]
Sounds good to me!
