### ISSUE TITLE
aeson Encoding for faster Bulk operations

### ISSUE THREAD

**Issue by andrewthad** [bitemyapp/bloodhound#148]
Currently, `Bulk` is defined as:

    data BulkOperation =
        BulkIndex  IndexName MappingName DocId Value
      | BulkCreate IndexName MappingName DocId Value
      | BulkDelete IndexName MappingName DocId
      | BulkUpdate IndexName MappingName DocId Value

I would like to add three new data constructors:

    data BulkOperation =
        BulkIndex  IndexName MappingName DocId Value
      | BulkCreate IndexName MappingName DocId Value
      | BulkDelete IndexName MappingName DocId
      | BulkUpdate IndexName MappingName DocId Value
      | BulkIndexEncoding  IndexName MappingName DocId Encoding
      | BulkCreateEncoding IndexName MappingName DocId Encoding
      | BulkUpdateEncoding IndexName MappingName DocId Encoding

These would use the `Encoding` type from `aeson-0.11` and onward. This would allow me to perform faster bulk operations `ToJSON` types that implement `toEncoding`. Would a PR with this change (and appropriate changes to the implementation of `bulk`) be accepted?

**Comment by bitemyapp** [comment]
Also potentially relevant is https://github.com/bitemyapp/bloodhound/pull/145

Your approach seems like it avoids breaking things for most users. Have you benchmarked that it makes things faster? Can you share anything from that?

/cc @MichaelXavier

**Comment by MichaelXavier** [comment]
I'm interested in the benchmarks too. I do like that this is backwards compatible, but I'm kind of curious how much speed there is to gain going from Value to Encoding and especially how relevant it is in the face of making network calls to ES (obviously you can mitigate this quite a bit by batching). Also, if we did go forward with this, it would be a good idea to document on the BulkOperation type why you'd use one over the other.

**Comment by andrewthad** [comment]
I haven't done any benchmarking yet. I had seen the note in the docs that bulk had been changed from taking a List to taking a Vector to reduce allocations, and I assumed that this would take it a step further. I don't have the time to put together a meaningful benchmark any time soon, but I can definitely cut a PR if you'd take it without evidence of better performance. Also, I'm probably going to try this out in a proprietary codebase in three weeks, so I can let you know the results of that, but I think factoring out a standalone benchmark that other people can run would be to time consuming.

**Comment by MichaelXavier** [comment]
@bitemyapp please weigh in but here's my proposal: since you're planning on doing this in a proprietary codebase anyways (presumably you'll just fork the repo), what if you made the minimal change you need as you outline here, try it out and get some mileage on it and make any adjustments as needed. If everything goes well, I can take your branch and add some simple benchmarks and see what they say. What I have in mind is to just have some fixed piece of data and add a benchmark that races the traditional API vs the new API at say 100, 1k, 10K records. However, if you're going to do this for your own codebase, I would recommend you write at least a super basic, not-necessarily-fit-for-PR benchmark to see if this change even matters, because it would suck if you did this work, I wrote the bench afterwards and there turned out to be no reason to do this change at all.

**Comment by andrewthad** [comment]
That's sounds fine with me. I can do a pretty basic internal benchmark and see if there's any noticeable speedup.

**Comment by bitemyapp** [comment]
@MichaelXavier this plan sounds amenable to me.

@andrewthad we've had this running precedent of changes that aren't obviously an improvement (UX changes, perf stuff) being run privately in a fork in production so that things get shaken out a bit. It sounds like the plan is good with you too, which is great.

Thanks everyone, waiting to hear what Andrew sees :+1:

**Comment by andrewthad** [comment]
In my application, I see a 10% speedup from using `BulkCreateEncoding`. Some of this is because I have a type `TextUtf8` that looks like this:

    newtype TextUtf8 = TextUtf8 ByteString

Calling `toEncoding` on this is basically a no-op, while `toJSON` has to decode it to make it `Text`, only to ultimately UTF8 encode it again. Obviously, avoiding the `Value` representation saves me some allocations as well, but I don't know how much of my 10% speed is attributed to that and how much is attributed to the trickery I'm doing with `Text`. Either way, I think this is worth merging.
