### ISSUE TITLE
Further releases to Hackage

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/bloodhound#187]
https://twitter.com/bitemyapp/status/878404011870867457

@MichaelXavier How would you feel about moving to git only releases with a final push that lets people know to look at the Git repository?

**Comment by MichaelXavier** [comment]
Doesn't that make the project pretty hard to use from non-stack repos? I think they'd have to use a sandbox and add-source, I think? I just wonder what causes most pain for users, the version meddling or the change in install process for anyone off the street.

**Comment by MichaelXavier** [comment]
I agree that they should be immutable from what information I have. If there's some sort of serious issue where a trustee has to become involved because attempts to contact the author of the library has failed, it seems like it would be preferable for them to create a new verison in accordance with PVP and release that than to modify a dependency in-place.

However, I'd venture a guess that a majority of users either won't take note of the notice about git-only releases or will take some time to notice. I'd actually be curious what percentage of users these days are using stack vs cabal, because maintaining git dependencies in plain cabal is quite burdensome as there is no officially endorsed way of doing it.

Between fiddling with version numbers, questionable recommendations on the sidebar of the subreddit and the official website, it seems at the end of the day the stewards of the language are apt to pull rank, do what they think is right and make everyone else deal with it. I'm not so sure that as an act of protest this will change anything. I honestly don't know what the right thing is.
