### ISSUE TITLE
Use Text instead of String in DocId, Server, IndexName, MappingName, etc.

### ISSUE THREAD

**Issue by ozataman** [bitemyapp/bloodhound#24]
Use of the String type is discouraged in favor of Text (unicode) in libraries and apps meant for production. It is particularly relevant in database libraries, as many use cases will manipulate millions of items per day, hitting problems with String in essentially a "tight loop".

**Comment by bitemyapp** [comment]
I'm open to this. The places where String are used are generally not where you'd have a tight loop - where I used String and Text was a conscious decision.

If it's causing slowdowns/problems I'd like to hear about that. Is this a case where you scanned the source code saw `String` and immediately decided to file the issue or are you testing Bloodhound and have identified excessive allocations/general slowness due to the use of String?

**Comment by ozataman** [comment]
My comment was from a review of the codebase coupled with some minimal, prototype usage to see if ES + bloodhound would be fit for an internal project. Nothing more than that.

Usage of Strings is a general eyesore in many settings (high volume code-paths being one) and an easy one to fix. I'm not sure why you went with that given you expose Text in several other places. Either way, I don't think this is a library breaking issue in its current form. It's probably a fairly small overhead compared to the IO-bound actions that are the meat of the functionality. It just caught my eye as an odd choice.

In our potential use, for example, we will be generating UUID-like things as document IDs and may have fairly long strings as a result. Let's say they are 32 characters long. Converting them to strings will mean a minimum of 32-64 non-local pointer dereferences for each DB operation, and that's assuming perfect list fusion. We'll make millions of such operations per day and others might have even larger volumes, as should be the assumption when designing DB bindings.

As an aside, If you do convert to Text, then you should also make sure they are not later converted to String, which would negate the benefit, but are actually copied directly to the output API in efficient form, probably using Builder.

**Comment by bitemyapp** [comment]
`DocId`s make a good case for the use of Text, if you're generating 128-bit UUIDs / flake ids - which I could hypothetically end up doing myself - https://github.com/bitemyapp/blacktip

This is why I prefer flake-style unique ids over UUID4: https://twitter.com/bitemyapp/status/561073371459244033

I'll leave this issue open to be resolved by a future PR.

**Comment by bitemyapp** [comment]
@ozataman I wanted to review and see if I could remember why I made some things `String` rather than `Text`.

I was using this convenience function:

http://hackage.haskell.org/package/http-client-0.4.7.1/docs/Network-HTTP-Client.html#v:parseUrl

Which defers to: http://hackage.haskell.org/package/http-client-0.4.7.1/docs/src/Network-HTTP-Client-Request.html#setUri

This raises the question for me of whether the parsing costs more time than the String allocation.

Which gets back to why I'd like a benchmark before attacking the problem, so I know what to attack. Do I need to write my own request construction helper from scratch that avoids the work of parsing, or do I just need to slide in ByteString where there was a String before, avoiding the packing & additional allocation?

**Comment by MichaelXavier** [comment]
I agree on all points about benchmarking, but if it turns out that uri parsing is a problem, we do have https://github.com/soostone/uri-bytestring

So if that turns out to be useful we could clean that library up for release, probably shed the safecopy dependency to maybe an instances package since safecopy is more of an application concern.
