### ISSUE TITLE
Server connection establishment - throws multiple errors

### ISSUE THREAD

**Issue by madhavan020985** [bitemyapp/bloodhound#46]
I wrote a sample code (to connect to elasticsearch server) that runs in the main module, here - https://github.com/madhavan020985/haskell-examples/blob/master/esearch/es_hello.hs#L17.

It throws at least three errors as,
es_hello.hs:16:1:    Couldn't match expected type ‘IO t1’ with actual type ‘a0 -> m0 a0’
es_hello.hs:17:18:    Couldn't match expected type ‘a -> t0’ with actual type ‘Server’
es_hello.hs:17:25:    Couldn't match expected type ‘Text’ with actual type ‘[Char]’

Does `Server` constructor expect Text (or) [Char]. 

This is a code, i took it straight from the Readme page. And i changed it a bit to run inside main instead of ghci....

**Comment by bitemyapp** [comment]
Please note examples such as you see here:

https://github.com/bitemyapp/bloodhound#create-index

Some things to keep in mind:

Server is a data constructor, not a function, you can just use `let` with no bind arrow `<-` to define a server.

`withBH` and `runBH` form connections, the difference between the two is explained in the example comments.

You need OverloadedStrings to use a `String` (which is an alias of `[Char]`) as if it were a `Text` value. Often when you see something about using a `String` as a `Text` or `ByteString` value, it's probably because you forgot `OverloadedStrings`. This extension is enabled in the example. I forget to turn it on in my GHCi REPL all the time :)

You can definitely make this run in main, just need to fix a few things up. Hope this helps!

**Comment by madhavan020985** [comment]
thanks, bitemyapp... your tips helped....
